-- 024: what each ruleset version actually CONTAINED.
--
-- DEPLOYMENT ORDER: not file order. See the header of
-- 020_freeze_risk_after_decision.sql and docs/deploy.md. This one is
-- independent of that sequence and can be applied at any point in it.
--
-- THE GAP
--
-- Every scored application stores risk_ruleset_version, and since migration 021
-- every decision stores the version it was taken under. Both are strings. What
-- the string MEANT — which points, which thresholds, which country lists —
-- lived only in worker/scoring.py and in git history.
--
-- An auditor cannot read git. "Decided under 2026-09-1" is only an answer if
-- 2026-09-1 is something you can look up, and until now the honest reply was
-- "clone the repository and check out the right commit". This table is that
-- lookup.
--
-- WHAT IS IN A ROW, AND WHAT IS DELIBERATELY NOT
--
-- points and thresholds are what scoring.py applies. reference_data is the data
-- scoring READS — the two FATF country lists, with their source, publication
-- date, plenary and digest where the repository records one.
--
-- The sanctions list is NOT in here, and that is not an omission. Scoring never
-- reads it: screening happens first and passes its hits in. Which list version
-- informed a particular decision is already recorded per screening run, in
-- screening_results.snapshot_id -> sanctions_snapshots, because it is a property
-- of that run rather than of the rules. A decision depends on both, and the two
-- are versioned in the two places they belong.
--
-- IMMUTABLE, THE SAME WAY audit_events IS
--
-- A ruleset definition that can be edited later defends nothing. The entire
-- value of this table is that "2026-09-1 contained these points" is a statement
-- nobody can quietly revise after a decision has been defended with it — which
-- is the same argument migration 006 makes about the audit log, so it gets the
-- same mechanism rather than a second style of guard.
--
-- Corrections are made by recording a NEW version and bumping
-- scoring.RULESET_VERSION, exactly as 2026-09-2 corrected 2026-09-1's country
-- list. That is also why there is no updated_at.
--
-- WHERE THE SEEDED CONTENT CAME FROM
--
-- Not from memory, and not retyped. The rows below were generated by reading
-- worker/scoring.py for the current version and `git show ea139d3:worker/
-- scoring.py` for the previous one, so the values in this file are the values
-- the code held.
--
-- The one judgement involved was whether 2026-09-1's points could be
-- established at all, since the module has changed since. An AST comparison of
-- every upper-case module constant across the version bump (commit f15c7dc)
-- shows that only the country lists and the version string differ: every points
-- table, threshold and match band is identical. The comment above
-- RULESET_VERSION asserts the same thing, and the history corroborates it
-- rather than the other way round.
--
-- 2026-09-1's reference data carries NULL publication dates. That is an
-- ESTABLISHED absence rather than an unknown one: that version's
-- increased-monitoring list was never published by FATF — it held Monaco
-- alongside Turkiye and the UAE, a combination never issued — and the
-- repository says so itself in the provenance text recorded in the row.

create table rulesets (
    version text primary key,

    -- When this version started applying. Taken from the commit that introduced
    -- it, which is the only date the repository can actually establish.
    --
    -- Seeded decisions carry decided_at values EARLIER than this, because the
    -- seeder backdates synthetic history to make the demo look lived-in. Real
    -- decisions could not. Left as the commit date rather than stretched
    -- backwards to cover the seed, because inventing an earlier date to make
    -- the data look tidy is the failure this table exists to prevent.
    effective_from timestamptz not null,

    -- The per-signal points as scoring.py defines them.
    points jsonb not null,

    -- auto_approve_below / auto_reject_at_or_above.
    thresholds jsonb not null,

    -- The lists scoring reads, with whatever provenance the repository records
    -- for each. Nullable fields inside are meaningful: a null published_at is
    -- the data saying it does not know, or knows there is none.
    reference_data jsonb,

    -- Why this version exists. Not blank, in the database, for the same reason
    -- decisions.reason is not blank: a version with no stated reason is a row
    -- that cannot be defended by whoever has to defend it.
    change_note text not null
        constraint rulesets_change_note_not_blank
        check (length(trim(change_note)) > 0),

    recorded_at timestamptz not null default now()
);

create function rulesets_immutable() returns trigger
language plpgsql as $$
begin
    raise exception 'rulesets is append-only: % is not permitted', tg_op
        using errcode = 'restrict_violation',
              hint = 'A ruleset definition that can be edited later defends '
                     'nothing. Record a new version and bump '
                     'scoring.RULESET_VERSION instead.';
end;
$$;

-- FOR EACH STATEMENT, following migration 006 exactly: the operation is banned
-- outright, so there is nothing to inspect, it fires even on a statement
-- matching zero rows, and it costs less.
create trigger rulesets_no_update
    before update on rulesets
    for each statement execute function rulesets_immutable();

create trigger rulesets_no_delete
    before delete on rulesets
    for each statement execute function rulesets_immutable();

create trigger rulesets_no_truncate
    before truncate on rulesets
    for each statement execute function rulesets_immutable();

-- ---------------------------------------------------------------------------
-- The versions that exist, generated from the repository
-- ---------------------------------------------------------------------------

insert into rulesets
    (version, effective_from, points, thresholds, reference_data, change_note)
values (
    '2026-09-1',
    '2026-09-17T20:34:07+02:00'::timestamptz,
    '{"adverse_media": {"confirmed": 10, "probable": 10, "weak": 5}, "country_call_for_action": 40, "country_increased_monitoring": 15, "document": {"Abandoned": 30, "Approved": 0, "Awaiting User": 20, "Declined": 40, "Expired": 30, "In Progress": 20, "In Review": 10, "Kyc Expired": 30, "Resubmitted": 20}, "document_missing": 30, "match_bands": {"confirmed_at": 92.0, "probable_at": 85.0, "weak_at": 80.0}, "pep": {"confirmed": 30, "probable": 15, "weak": 5}, "sanctions": {"confirmed": 60, "probable": 45, "weak": 20}}'::jsonb,
    '{"auto_approve_below": 20, "auto_reject_at_or_above": 80}'::jsonb,
    '{"fatf_call_for_action": {"codes": ["IR", "KP", "MM"], "digest": null, "plenary": null, "provenance": "UNSOURCED \u2014 INVENTED, NOT SOURCED. Written from memory when the scoring module was built; never fetched from fatf-gafi.org, never cited to a plenary statement. Decisions carrying ruleset 2026-09-1 were scored against this list. Retained verbatim because it is what those decisions were actually scored against. The repository''s own description of it, written when it was replaced, follows: UNSOURCED. These codes are demo data and do not transcribe any FATF revision. They cannot: the increased-monitoring set holds Monaco, grey-listed at the June 2024 plenary, beside Turkiye and the United Arab Emirates, de-listed at that same plenary and in February 2024 respectively \u2014 a combination FATF never published. The call-for-action set (IR, KP, MM) does match the real one, which has been those three since Myanmar was added in October 2022. Rather than assign a publication date that would make the whole thing look sourced, published_at is null. Before any real use: replace both sets from source_url and set published_at to that plenary''s own date.", "published_at": null, "retrieved_at": null, "source_url": "https://www.fatf-gafi.org/en/topics/high-risk-and-other-monitored-jurisdictions.html", "sourcing": "unsourced"}, "fatf_increased_monitoring": {"codes": ["AE", "BF", "CD", "CM", "HR", "HT", "MC", "ML", "MZ", "NA", "NG", "PH", "SN", "SS", "SY", "TR", "TZ", "UG", "VN", "YE", "ZA"], "digest": null, "plenary": null, "provenance": "UNSOURCED \u2014 INVENTED, NOT SOURCED. Written from memory when the scoring module was built; never fetched from fatf-gafi.org, never cited to a plenary statement. Decisions carrying ruleset 2026-09-1 were scored against this list. Retained verbatim because it is what those decisions were actually scored against. The repository''s own description of it, written when it was replaced, follows: UNSOURCED. These codes are demo data and do not transcribe any FATF revision. They cannot: the increased-monitoring set holds Monaco, grey-listed at the June 2024 plenary, beside Turkiye and the United Arab Emirates, de-listed at that same plenary and in February 2024 respectively \u2014 a combination FATF never published. The call-for-action set (IR, KP, MM) does match the real one, which has been those three since Myanmar was added in October 2022. Rather than assign a publication date that would make the whole thing look sourced, published_at is null. Before any real use: replace both sets from source_url and set published_at to that plenary''s own date.", "published_at": null, "retrieved_at": null, "source_url": "https://www.fatf-gafi.org/en/topics/high-risk-and-other-monitored-jurisdictions.html", "sourcing": "unsourced"}}'::jsonb,
    'DECISIONS UNDER THIS VERSION WERE SCORED AGAINST AN UNSOURCED COUNTRY LIST. The increased-monitoring set was written from memory when the scoring module was built in Phase 5 (commit 4910619, 2026-09-17). It was never fetched from fatf-gafi.org and never cited to a plenary statement. The comment above it read ''FATF listings, as at 2026-09'', which implied a currency it never had. It cannot correspond to any real publication: it held Monaco, grey-listed at the June 2024 plenary, beside Turkiye and the United Arab Emirates, de-listed at that same plenary and in February 2024 respectively. FATF has never issued that combination. The error stood from 2026-09-17 until it was checked against the source on 2026-09-24 and replaced by 2026-09-2. The call-for-action set (IR, KP, MM) happens to match the real one, which has been those three since Myanmar was added in October 2022, but it was not sourced either. Points, thresholds and match bands ARE established: an AST comparison of every upper-case module constant across the version bump (commit f15c7dc) shows only the country lists and the version string differ, and the codes are byte-identical between Phase 5 and commit ea139d3, so this version had one set of codes throughout its life. Publication dates are null because there is none to record, not because the repository failed to keep one. effective_from is the commit date; seeded decisions carry earlier decided_at values because the seeder backdates synthetic history.'
);

insert into rulesets
    (version, effective_from, points, thresholds, reference_data, change_note)
values (
    '2026-09-2',
    '2026-09-24T16:37:05+02:00'::timestamptz,
    '{"adverse_media": {"confirmed": 10, "probable": 10, "weak": 5}, "country_call_for_action": 40, "country_increased_monitoring": 15, "document": {"Abandoned": 30, "Approved": 0, "Awaiting User": 20, "Declined": 40, "Expired": 30, "In Progress": 20, "In Review": 10, "Kyc Expired": 30, "Resubmitted": 20}, "document_missing": 30, "match_bands": {"confirmed_at": 92.0, "probable_at": 85.0, "weak_at": 80.0}, "pep": {"confirmed": 30, "probable": 15, "weak": 5}, "sanctions": {"confirmed": 60, "probable": 45, "weak": 20}}'::jsonb,
    '{"auto_approve_below": 20, "auto_reject_at_or_above": 80}'::jsonb,
    '{"fatf_call_for_action": {"codes": ["IR", "KP", "MM"], "digest": "a7a319093b050cec1a1cf0db7b087a113acd2e512ffb35c39e96710a5cc3f74c", "plenary": null, "provenance": "UNSOURCED. Not re-fetched during the 2026-09-24 correction: the FATF call-for-action statement returned HTTP 403. IR, KP and MM have been the set since Myanmar was added at the October 2022 plenary, but no publication date is claimed for them here. To close this, fetch the current statement and set published_at to its plenary date.", "published_at": null, "retrieved_at": null, "source_url": "https://www.fatf-gafi.org/en/topics/high-risk-and-other-monitored-jurisdictions.html", "sourcing": "unsourced"}, "fatf_increased_monitoring": {"codes": ["AO", "BA", "BG", "BO", "CD", "CI", "CM", "HT", "IQ", "KE", "KW", "LA", "LB", "MC", "NP", "PG", "SS", "SY", "VE", "VG", "VN", "YE"], "digest": "c8e4e1edab7aec194195b15d30a56fd1c1fb0123c674095d1f3a5156000aea02", "plenary": "June 2026", "provenance": "Complete set from the FATF statement ''Jurisdictions under Increased Monitoring'', Paris, 19 June 2026, retrieved from source_url on 2026-09-24. All 22 codes come from that one statement; none is carried over from an earlier one.", "published_at": "2026-06-19", "retrieved_at": "2026-09-24", "source_url": "https://www.fatf-gafi.org/content/fatf-gafi/en/publications/High-risk-and-other-monitored-jurisdictions/increased-monitoring-june-2026.html", "sourcing": "sourced"}}'::jsonb,
    'Replaced the fabricated increased-monitoring set with the complete set from one FATF statement: Jurisdictions under Increased Monitoring, Paris, 19 June 2026, retrieved 2026-09-24. 13 codes removed, 14 added, 8 unchanged. No points, thresholds or match bands changed — the version moved because the reference data it reads changed materially, and leaving it would have meant two decisions stamped 2026-09-1 scored against two different country lists. The call-for-action set was deliberately not re-fetched: its FATF statement returned HTTP 403, so it keeps a null publication date and says UNSOURCED rather than borrowing the monitoring list''s date.'
);

-- ---------------------------------------------------------------------------
-- The references, added AFTER the seed so the existing rows satisfy them
-- ---------------------------------------------------------------------------
--
-- Both are nullable columns, so a NULL still means "not established" and is
-- still permitted — a foreign key constrains values that are present, which is
-- exactly the behaviour wanted here. Migration 021 deliberately leaves the
-- decision column NULL where the data could not establish a version, and that
-- must stay legal.
--
-- These make the lookup real rather than conventional: with them, a version
-- string on an application or a decision cannot name a ruleset nobody wrote
-- down. Without them, the next version bump could ship a string pointing at
-- nothing and the table would quietly stop being an answer.

alter table applications
    add constraint applications_ruleset_version_known
    foreign key (risk_ruleset_version) references rulesets (version);

alter table decisions
    add constraint decisions_ruleset_version_known
    foreign key (risk_ruleset_version_at_decision) references rulesets (version);
