// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/apply" | "/desk" | "/desk/[id]" | "/health" | "/login" | "/mock-vendor/verify/[token]" | "/stats" | "/status/[id]" | "/verify/[id]"
type AppRouteHandlerRoutes = "/api/mock-vendor/v3/session" | "/api/mock-vendor/v3/session/[id]/decision" | "/api/webhooks/didit"
type PageRoutes = never
type LayoutRoutes = "/" | "/desk"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/mock-vendor/v3/session": {}
  "/api/mock-vendor/v3/session/[id]/decision": { "id": string; }
  "/api/webhooks/didit": {}
  "/apply": {}
  "/desk": {}
  "/desk/[id]": { "id": string; }
  "/health": {}
  "/login": {}
  "/mock-vendor/verify/[token]": { "token": string; }
  "/stats": {}
  "/status/[id]": { "id": string; }
  "/verify/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/desk": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
